version: '3'

volumes:
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: code_quality_service_production_django
    env_file:
      - ./.env
    volumes:
      - ./logs/:/app/logs
      - ./keys/:/app/keys
      - ./fixtures/:/app/fixtures
      - ./media/:/app/media
      - ./staticfiles/:/app/staticfiles
    command: /start-server

  traefik:
    build:
      context: .
      dockerfile: ./docker/traefik/Dockerfile
    image: code_quality_service_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"


  celeryworker:
    <<: *django
    image: code_quality_service_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: code_quality_service_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: code_quality_service_production_flower
    command: /start-flower
