# Generated by Django 4.1.7 on 2023-02-26 14:54

import uuid

import django.core.validators
from django.db import migrations, models

import files.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeFile",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=files.models.file_handler,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["py"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
